// Snapshot of Task Mining adoption pulled from Datadog (celonis.datadoghq.com).
// Period: Jul-Aug 2026 (2026-07-27 - 2026-08-10).
// Log-derived figures (clients, teams, versions, errors, weekly) reflect the
// retained Datadog log window (data present from ~2026-07-27). Project-creation
// trend uses metric retention (2026-06-18 - 2026-08-10).
// Generated by scripts/refresh_aug10.py - do not edit by hand.

export const PERIOD = "Jul-Aug 2026";
export const PERIOD_RANGE = "2026-07-27 - 2026-08-10";
export const SOURCE = "Datadog - celonis.datadoghq.com";

export interface SummaryMetrics {
  activeClients: number;
  activeTeams: number;
  suspendedClients: number;
  projectCreations: number;
}

export const summary: SummaryMetrics = {
  activeClients: 5486,
  activeTeams: 95,
  suspendedClients: 0,
  projectCreations: 5555,
};

export interface TrendPoint {
  day: number;
  count: number;
}

// sum:taskmining.project.creations.as_count(), daily rollup (metric window).
export const creationTrend: TrendPoint[] = [
  143, 96, 0, 0, 312, 147, 219, 73, 55, 0, 1, 110, 95, 163, 229, 75, 0, 0, 186, 87, 218, 60, 87, 0, 0, 132, 94, 297, 116, 49, 4, 5, 265, 219, 110, 57, 211, 0, 0, 194, 222, 67, 115, 70, 2, 0, 123, 87, 309, 125, 171, 7, 5, 143,
].map((count, i) => ({ day: i + 1, count }));

export interface VersionPoint {
  version: string;
  clients: number;
}

// Distinct @clientId per @recorderVersion (purpose:prod), top versions.
export const versionMix: VersionPoint[] = [
  { version: "2.21.1.0", clients: 2546 },
  { version: "2.21.0.0", clients: 1162 },
  { version: "2.20.0.0", clients: 878 },
  { version: "2.18.2.0", clients: 310 },
  { version: "2.17.1.0", clients: 166 },
  { version: "2.17.0.0", clients: 86 },
  { version: "2.18.0.0", clients: 62 },
  { version: "2.17.1.251", clients: 55 },
  { version: "2.18.1.0", clients: 53 },
  { version: "2.19.0.0", clients: 49 },
  { version: "2.21.2.0", clients: 43 },
  { version: "2.15.2.0", clients: 18 },
  { version: "2.10.0.0", clients: 15 },
  { version: "2.13.0.0", clients: 11 },
  { version: "2.20.1.0", clients: 10 },
];

export interface WeekPoint {
  week: string;
  clients: number;
}

// Partial: only the most recent weeks fall inside log retention.
export const weeklyActiveClients: WeekPoint[] = [
  { week: "Jul 27", clients: 3782 },
  { week: "Aug 3", clients: 4685 },
  { week: "Aug 10", clients: 3900 },
];

export interface TeamRecord {
  team: string;
  clients: number;
  versions: number;
  parquet: number;
  image: number;
  errors: number;
}

// All 95 teams active on the Task Mining client in production during
// the window. parquet/image upload counts are not part of this refresh (0).
export const teams: TeamRecord[] = [
  { team: "nykredit-realkredit", clients: 1814, versions: 2, parquet: 0, image: 0, errors: 48919 },
  { team: "majid-ai-futtaim", clients: 812, versions: 3, parquet: 0, image: 0, errors: 28955 },
  { team: "prod", clients: 453, versions: 1, parquet: 0, image: 0, errors: 43602 },
  { team: "allianz-global", clients: 375, versions: 4, parquet: 0, image: 0, errors: 2425729 },
  { team: "refinitiv", clients: 327, versions: 5, parquet: 0, image: 0, errors: 23689 },
  { team: "allstate", clients: 191, versions: 3, parquet: 0, image: 0, errors: 120721 },
  { team: "nec-corporation-2", clients: 188, versions: 3, parquet: 0, image: 0, errors: 369058 },
  { team: "ofi-benelux-b-v--om-kaemingk-c4c", clients: 168, versions: 1, parquet: 0, image: 0, errors: 2259 },
  { team: "kapitus", clients: 165, versions: 6, parquet: 0, image: 0, errors: 135221 },
  { team: "anglo-american", clients: 161, versions: 8, parquet: 0, image: 0, errors: 785654 },
  { team: "production", clients: 131, versions: 4, parquet: 0, image: 0, errors: 50740 },
  { team: "astrazeneca-dev", clients: 89, versions: 3, parquet: 0, image: 0, errors: 195729 },
  { team: "dbank", clients: 69, versions: 1, parquet: 0, image: 0, errors: 2593 },
  { team: "mol", clients: 59, versions: 5, parquet: 0, image: 0, errors: 13877 },
  { team: "unilever-genpact", clients: 38, versions: 1, parquet: 0, image: 0, errors: 1166 },
  { team: "dai-ichi-life-insurance", clients: 36, versions: 1, parquet: 0, image: 0, errors: 825502 },
  { team: "schlumberger", clients: 28, versions: 5, parquet: 0, image: 0, errors: 45676 },
  { team: "toyo-seikan", clients: 26, versions: 1, parquet: 0, image: 0, errors: 49764 },
  { team: "manulife-pov-ca-pov", clients: 24, versions: 1, parquet: 0, image: 0, errors: 658 },
  { team: "aflac", clients: 22, versions: 4, parquet: 0, image: 0, errors: 46080 },
  { team: "kimberlyclark", clients: 22, versions: 7, parquet: 0, image: 0, errors: 16199 },
  { team: "elsevier", clients: 20, versions: 1, parquet: 0, image: 0, errors: 6525 },
  { team: "fujitsu-limited-product-business-task-mining-c4c", clients: 19, versions: 1, parquet: 0, image: 0, errors: 2219 },
  { team: "endpoint", clients: 16, versions: 3, parquet: 0, image: 0, errors: 16411 },
  { team: "siemens-sandbox", clients: 16, versions: 4, parquet: 0, image: 0, errors: 405 },
  { team: "caceis-task-mining-pov", clients: 16, versions: 3, parquet: 0, image: 0, errors: 70 },
  { team: "schlumberger-qa", clients: 14, versions: 2, parquet: 0, image: 0, errors: 13185 },
  { team: "kn-sb", clients: 12, versions: 3, parquet: 0, image: 0, errors: 208 },
  { team: "coloplast-pov", clients: 12, versions: 1, parquet: 0, image: 0, errors: 90 },
  { team: "amgen", clients: 11, versions: 4, parquet: 0, image: 0, errors: 1644 },
  { team: "novartis-sb", clients: 9, versions: 1, parquet: 0, image: 0, errors: 276 },
  { team: "consulting", clients: 8, versions: 1, parquet: 0, image: 0, errors: 129 },
  { team: "kn", clients: 7, versions: 1, parquet: 0, image: 0, errors: 922 },
  { team: "dpdhl", clients: 6, versions: 1, parquet: 0, image: 0, errors: 191 },
  { team: "pepsico-prod", clients: 6, versions: 3, parquet: 0, image: 0, errors: 139 },
  { team: "riverty", clients: 6, versions: 1, parquet: 0, image: 0, errors: 21 },
  { team: "telefonica-productive", clients: 6, versions: 1, parquet: 0, image: 0, errors: 23889 },
  { team: "eon", clients: 6, versions: 3, parquet: 0, image: 0, errors: 53 },
  { team: "upm-sandbox", clients: 5, versions: 2, parquet: 0, image: 0, errors: 110 },
  { team: "banco-pichincha", clients: 5, versions: 1, parquet: 0, image: 0, errors: 754 },
  { team: "ibm-crossmark-c4c", clients: 5, versions: 1, parquet: 0, image: 0, errors: 765 },
  { team: "kistler-prod", clients: 4, versions: 1, parquet: 0, image: 0, errors: 3491 },
  { team: "bouygues-telecom", clients: 4, versions: 1, parquet: 0, image: 0, errors: 75 },
  { team: "envalior", clients: 4, versions: 1, parquet: 0, image: 0, errors: 67628 },
  { team: "sandbox", clients: 4, versions: 3, parquet: 0, image: 0, errors: 81 },
  { team: "merck-tst", clients: 3, versions: 1, parquet: 0, image: 0, errors: 199 },
  { team: "alstom", clients: 3, versions: 2, parquet: 0, image: 0, errors: 45 },
  { team: "productive", clients: 3, versions: 1, parquet: 0, image: 0, errors: 926736 },
  { team: "eight-japan-engineering-consultants", clients: 3, versions: 1, parquet: 0, image: 0, errors: 293 },
  { team: "payroll-task-mining", clients: 2, versions: 1, parquet: 0, image: 0, errors: 20 },
  { team: "task-mining-demo---kay", clients: 2, versions: 2, parquet: 0, image: 0, errors: 4 },
  { team: "diot-siaci", clients: 2, versions: 1, parquet: 0, image: 0, errors: 9 },
  { team: "cel-tm-finance", clients: 2, versions: 2, parquet: 0, image: 0, errors: 16 },
  { team: "dbank-psb", clients: 2, versions: 1, parquet: 0, image: 0, errors: 20 },
  { team: "itochu-partner-sandbox", clients: 2, versions: 2, parquet: 0, image: 0, errors: 138 },
  { team: "silamir-partner-sandbox", clients: 2, versions: 1, parquet: 0, image: 0, errors: 11 },
  { team: "booking-holdings", clients: 2, versions: 1, parquet: 0, image: 0, errors: 40 },
  { team: "task-mining", clients: 2, versions: 2, parquet: 0, image: 0, errors: 4449 },
  { team: "ilt-saint-gobain-training", clients: 1, versions: 1, parquet: 0, image: 0, errors: 1 },
  { team: "dataops", clients: 1, versions: 1, parquet: 0, image: 0, errors: 33 },
  { team: "hanwhasolution-pov", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "celonis-rktu9q", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
  { team: "ibm-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 83 },
  { team: "jc14jlpc-2026-04-03", clients: 1, versions: 1, parquet: 0, image: 0, errors: 12 },
  { team: "wilo-sb", clients: 1, versions: 1, parquet: 0, image: 0, errors: 29 },
  { team: "hitachi-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 942 },
  { team: "metro-bank", clients: 1, versions: 1, parquet: 0, image: 0, errors: 33 },
  { team: "banco-santander", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
  { team: "fnfh2u42-2025-04-18", clients: 1, versions: 1, parquet: 0, image: 0, errors: 85 },
  { team: "a-gutte-celonis-com", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "pyze-partner-sandbox2", clients: 1, versions: 1, parquet: 0, image: 0, errors: 45 },
  { team: "kpdgk5yo-2025-12-12", clients: 1, versions: 1, parquet: 0, image: 0, errors: 4 },
  { team: "ems-japan-pov", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "panasonic-information", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
  { team: "nomura-research-institute-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 3 },
  { team: "michelin", clients: 1, versions: 1, parquet: 0, image: 0, errors: 23 },
  { team: "optus-standard-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "nationwide-prod", clients: 1, versions: 1, parquet: 0, image: 0, errors: 6 },
  { team: "accenture-development-sandbox-dcp", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "bouygues-telecom-pov-network-pov", clients: 1, versions: 1, parquet: 0, image: 0, errors: 44 },
  { team: "ciklum-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
  { team: "zespri", clients: 1, versions: 1, parquet: 0, image: 0, errors: 4 },
  { team: "m-sakamoto-celonis-com", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "axa-task-mining", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
  { team: "tata-consultancy-services-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 567 },
  { team: "syngenta-prod", clients: 1, versions: 1, parquet: 0, image: 0, errors: 502 },
  { team: "cordesgraefe", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2376542 },
  { team: "allianzconsult-prod", clients: 1, versions: 1, parquet: 0, image: 0, errors: 19 },
  { team: "mondelez", clients: 1, versions: 1, parquet: 0, image: 0, errors: 100 },
  { team: "tgt-internal", clients: 1, versions: 1, parquet: 0, image: 0, errors: 0 },
  { team: "logatik-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 9 },
  { team: "roboyo-us-partner-sandbox", clients: 1, versions: 1, parquet: 0, image: 0, errors: 26 },
  { team: "basf", clients: 1, versions: 1, parquet: 0, image: 0, errors: 18 },
  { team: "tpl-product-task-mining", clients: 1, versions: 1, parquet: 0, image: 0, errors: 32 },
  { team: "kone", clients: 1, versions: 1, parquet: 0, image: 0, errors: 2 },
];
