// Per-customer view: contract value (from 'Customers Task mining.xlsx') joined
// with current adoption (active clients) from the Datadog May 2026 snapshot.
// Generated by scripts/build_customers.py - do not edit by hand.

export interface CustomerRecord {
  customer: string;
  contractValue: number; // current ACV (USD), 0 = none on record
  activeClients: number; // distinct active clients, Datadog May 2026
  endDate: string | null; // contract end (latest active subscription)
  active: boolean; // has >=1 active subscription
  matchedTeams: string[]; // Datadog @teamDomain(s) joined for adoption
}

export const customers: CustomerRecord[] = [
  {
    "customer": "Cardinal Health Inc.",
    "contractValue": 1000000,
    "activeClients": 0,
    "endDate": "2031-03-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Chevron Corporation",
    "contractValue": 961371,
    "activeClients": 0,
    "endDate": "2028-08-11",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Novartis AG",
    "contractValue": 303465,
    "activeClients": 0,
    "endDate": "2027-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "MANN+HUMMEL GmbH",
    "contractValue": 210040,
    "activeClients": 0,
    "endDate": "2030-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Metro Bank PLC",
    "contractValue": 186116,
    "activeClients": 0,
    "endDate": "2028-03-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Nykredit Realkredit A/S",
    "contractValue": 172593,
    "activeClients": 226,
    "endDate": "2027-05-01",
    "active": true,
    "matchedTeams": [
      "nykredit-realkredit"
    ]
  },
  {
    "customer": "Booking Holdings Inc.",
    "contractValue": 147490,
    "activeClients": 2,
    "endDate": "2027-02-26",
    "active": true,
    "matchedTeams": [
      "booking-holdings"
    ]
  },
  {
    "customer": "Mondelez Europe Procurement GmbH",
    "contractValue": 143574,
    "activeClients": 1,
    "endDate": "2030-07-31",
    "active": true,
    "matchedTeams": [
      "mondelez"
    ]
  },
  {
    "customer": "Allianz Technology SE",
    "contractValue": 141600,
    "activeClients": 648,
    "endDate": "2027-04-01",
    "active": true,
    "matchedTeams": [
      "allianz-global"
    ]
  },
  {
    "customer": "The Dai-ichi Life Insurance Company, Limited",
    "contractValue": 128000,
    "activeClients": 40,
    "endDate": "2026-07-31",
    "active": true,
    "matchedTeams": [
      "dai-ichi-life-insurance"
    ]
  },
  {
    "customer": "Endpoint Technologies, LLC",
    "contractValue": 119183,
    "activeClients": 11,
    "endDate": "2026-07-01",
    "active": true,
    "matchedTeams": [
      "endpoint"
    ]
  },
  {
    "customer": "BMW AG",
    "contractValue": 103028,
    "activeClients": 0,
    "endDate": "2027-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Allstate Insurance Company",
    "contractValue": 96756,
    "activeClients": 137,
    "endDate": "2026-06-30",
    "active": true,
    "matchedTeams": [
      "allstate"
    ]
  },
  {
    "customer": "Deutsche Bank AG",
    "contractValue": 82600,
    "activeClients": 53,
    "endDate": "2027-01-01",
    "active": true,
    "matchedTeams": [
      "dbank",
      "dbank-psb"
    ]
  },
  {
    "customer": "Anglo American PLC",
    "contractValue": 82500,
    "activeClients": 146,
    "endDate": "2026-12-01",
    "active": true,
    "matchedTeams": [
      "anglo-american"
    ]
  },
  {
    "customer": "ICA Gruppen",
    "contractValue": 61118,
    "activeClients": 0,
    "endDate": "2027-04-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Standard Bank Group",
    "contractValue": 50000,
    "activeClients": 0,
    "endDate": "2028-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Clifford Chance LLP",
    "contractValue": 47906,
    "activeClients": 0,
    "endDate": "2026-08-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Kapitus",
    "contractValue": 46659,
    "activeClients": 137,
    "endDate": "2027-11-15",
    "active": true,
    "matchedTeams": [
      "kapitus"
    ]
  },
  {
    "customer": "TARGET CORPORATION INDIA PRIVATE LIMITED",
    "contractValue": 42263,
    "activeClients": 0,
    "endDate": "2026-11-12",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "AGRANA Beteiligungs-AG",
    "contractValue": 30426,
    "activeClients": 0,
    "endDate": "2028-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Kimberly-Clark Corporation",
    "contractValue": 25000,
    "activeClients": 31,
    "endDate": "2026-11-01",
    "active": true,
    "matchedTeams": [
      "kimberlyclark"
    ]
  },
  {
    "customer": "UPM-Kymmene Oyj",
    "contractValue": 21194,
    "activeClients": 7,
    "endDate": "2029-01-31",
    "active": true,
    "matchedTeams": [
      "upm-sandbox"
    ]
  },
  {
    "customer": "Eight-Japan Engineering Consultants Inc.",
    "contractValue": 18106,
    "activeClients": 3,
    "endDate": "2030-07-31",
    "active": true,
    "matchedTeams": [
      "eight-japan-engineering-consultants"
    ]
  },
  {
    "customer": "Pacific International Lines",
    "contractValue": 14264,
    "activeClients": 0,
    "endDate": "2029-04-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Boehringer Ingelheim GmbH",
    "contractValue": 10502,
    "activeClients": 0,
    "endDate": "2029-01-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Perficient, Inc.",
    "contractValue": 103,
    "activeClients": 0,
    "endDate": "2027-05-02",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Refinitiv",
    "contractValue": 0,
    "activeClients": 577,
    "endDate": "2024-09-21",
    "active": false,
    "matchedTeams": [
      "refinitiv"
    ]
  },
  {
    "customer": "Majid Al Futtaim Global Solutions LLC (UAE)",
    "contractValue": 0,
    "activeClients": 231,
    "endDate": "2029-01-01",
    "active": true,
    "matchedTeams": [
      "majid-ai-futtaim"
    ]
  },
  {
    "customer": "ASTRAZENECA UK LIMITED",
    "contractValue": 0,
    "activeClients": 71,
    "endDate": "2025-12-30",
    "active": false,
    "matchedTeams": [
      "astrazeneca-dev"
    ]
  },
  {
    "customer": "MOL Group",
    "contractValue": 0,
    "activeClients": 62,
    "endDate": "2027-07-01",
    "active": true,
    "matchedTeams": [
      "mol"
    ]
  },
  {
    "customer": "SLB",
    "contractValue": 0,
    "activeClients": 46,
    "endDate": "2027-01-01",
    "active": true,
    "matchedTeams": [
      "schlumberger",
      "schlumberger-qa"
    ]
  },
  {
    "customer": "AFLAC LIFE INSURANCE JAPAN LTD.",
    "contractValue": 0,
    "activeClients": 38,
    "endDate": "2027-01-01",
    "active": true,
    "matchedTeams": [
      "aflac"
    ]
  },
  {
    "customer": "Siemens Financial Services GmbH",
    "contractValue": 0,
    "activeClients": 8,
    "endDate": "2026-10-01",
    "active": true,
    "matchedTeams": [
      "siemens-sandbox"
    ]
  },
  {
    "customer": "Deutsche Post AG Finance & HR Operations Deutschland",
    "contractValue": 0,
    "activeClients": 6,
    "endDate": "2026-01-07",
    "active": false,
    "matchedTeams": [
      "dpdhl"
    ]
  },
  {
    "customer": "Telefonica Global Technology",
    "contractValue": 0,
    "activeClients": 6,
    "endDate": "2026-01-01",
    "active": false,
    "matchedTeams": [
      "telefonica-productive"
    ]
  },
  {
    "customer": "Merck & Co., Inc.",
    "contractValue": 0,
    "activeClients": 4,
    "endDate": "2026-01-12",
    "active": false,
    "matchedTeams": [
      "merck-tst"
    ]
  },
  {
    "customer": "Rabobank",
    "contractValue": 0,
    "activeClients": 3,
    "endDate": "2027-01-01",
    "active": true,
    "matchedTeams": [
      "rabobank",
      "rabobank-sb"
    ]
  },
  {
    "customer": "DIOT SIACI",
    "contractValue": 0,
    "activeClients": 2,
    "endDate": "2027-03-13",
    "active": true,
    "matchedTeams": [
      "diot-siaci"
    ]
  },
  {
    "customer": "Goldman Sachs",
    "contractValue": 0,
    "activeClients": 2,
    "endDate": "2027-07-30",
    "active": true,
    "matchedTeams": [
      "gs-training-2026"
    ]
  },
  {
    "customer": "MICHELIN",
    "contractValue": 0,
    "activeClients": 2,
    "endDate": "2025-02-01",
    "active": false,
    "matchedTeams": [
      "michelin"
    ]
  },
  {
    "customer": "Nationwide Mutual Insurance Company",
    "contractValue": 0,
    "activeClients": 1,
    "endDate": "2028-11-25",
    "active": true,
    "matchedTeams": [
      "nationwide-prod"
    ]
  },
  {
    "customer": "PANASONIC INFORMATION SYSTEMS CO. LTD.",
    "contractValue": 0,
    "activeClients": 1,
    "endDate": "2025-11-01",
    "active": false,
    "matchedTeams": [
      "panasonic-information"
    ]
  },
  {
    "customer": "AB Electrolux",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-01-29",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Aldi Süd",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2029-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Amazon.com, Inc.",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-09-15",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "American National Insurance Company Inc",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-03-08",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "AXA Versicherungen AG",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2027-01-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Axpo Services AG",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-01-15",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "B3 S.A. - BRASIL, BOLSA, BALCAO",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-12-18",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Bank of America Corporation",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-12-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Citibank N.A.",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2029-03-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "DuPont",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-05-01",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "DÖHLER GmbH",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2029-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Flora Food Group BV",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-01-16",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "GSK PLC",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2028-01-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "ICICI HOME FINANCE COMPANY LIMITED",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2027-07-30",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Ingka Group",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-01-31",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "KB Life Insurance Co., Ltd.",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2028-07-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "KPMG US",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2024-10-01",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "London Stock Exchange Group PLC",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-01-01",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Morgan Stanley",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2027-10-30",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Novo Nordisk A/S",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2028-10-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "RUBIX GROUP INTERNATIONAL LIMITED",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-08-31",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "SASOL AFRICA",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2027-02-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "SKY UK LIMITED",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-01-31",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "SoftBank Corp.",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-02-01",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Tech Mahindra Global",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2024-11-30",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Telenor Sverige AB",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2023-10-05",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "ThyssenKrupp Rasselstein GmbH",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2027-10-01",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Vodafone Group Plc",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2025-01-26",
    "active": false,
    "matchedTeams": []
  },
  {
    "customer": "Wells Fargo & Company",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-07-31",
    "active": true,
    "matchedTeams": []
  },
  {
    "customer": "Wilhelmsen Global Business Services AS",
    "contractValue": 0,
    "activeClients": 0,
    "endDate": "2026-12-01",
    "active": true,
    "matchedTeams": []
  }
];
