// Recorder version adoption per customer, from Datadog (service:task-mining).
// Period: Jun 1-25, 2026. Distinct @clientId per (@teamDomain, @recorderVersion).
// Generated by scripts/build_versions.py - do not edit by hand.

import type { VersionPoint } from "@/data/adoption";

export const VERSION_PERIOD = "Jun 1-25, 2026";

export const versionTotals: VersionPoint[] = [
  {
    "version": "2.20.0.0",
    "clients": 955
  },
  {
    "version": "2.18.1.0",
    "clients": 666
  },
  {
    "version": "2.21.0.0",
    "clients": 588
  },
  {
    "version": "2.18.2.0",
    "clients": 491
  },
  {
    "version": "2.21.1.0",
    "clients": 344
  },
  {
    "version": "2.13.0.0",
    "clients": 242
  },
  {
    "version": "2.17.1.0",
    "clients": 195
  },
  {
    "version": "2.17.0.0",
    "clients": 108
  },
  {
    "version": "2.18.0.0",
    "clients": 73
  },
  {
    "version": "2.19.0.0",
    "clients": 58
  },
  {
    "version": "2.17.1.251",
    "clients": 57
  },
  {
    "version": "anyClientVersion",
    "clients": 42
  },
  {
    "version": "2.15.2.0",
    "clients": 20
  },
  {
    "version": "2.10.0.0",
    "clients": 19
  },
  {
    "version": "2.20.1.0",
    "clients": 13
  },
  {
    "version": "2.11.0.0",
    "clients": 13
  },
  {
    "version": "2.6.1.0",
    "clients": 10
  },
  {
    "version": "2.22.0.0",
    "clients": 8
  },
  {
    "version": "2.14.0.0",
    "clients": 4
  },
  {
    "version": "2.9.2.0",
    "clients": 2
  },
  {
    "version": "2.20.0",
    "clients": 2
  },
  {
    "version": "2.12.0.0",
    "clients": 2
  },
  {
    "version": "2.7.6.0",
    "clients": 1
  },
  {
    "version": "2.15.1.0",
    "clients": 1
  },
  {
    "version": "2.3.0.0",
    "clients": 1
  },
  {
    "version": "2.21.2.384",
    "clients": 1
  },
  {
    "version": "2.15.0.0",
    "clients": 1
  },
  {
    "version": "2.21.1.379",
    "clients": 1
  },
  {
    "version": "0.0.0-sim",
    "clients": 1
  },
  {
    "version": "2.8.1.0",
    "clients": 1
  }
];

export interface TeamVersions {
  team: string;
  clients: number;
  versions: VersionPoint[];
}

export const versionsByTeam: TeamVersions[] = [
  {
    "team": "allianz-global",
    "clients": 656,
    "versions": [
      {
        "version": "2.18.1.0",
        "clients": 654
      },
      {
        "version": "2.20.0.0",
        "clients": 1
      },
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "refinitiv",
    "clients": 510,
    "versions": [
      {
        "version": "2.18.2.0",
        "clients": 475
      },
      {
        "version": "2.17.1.0",
        "clients": 28
      },
      {
        "version": "2.15.2.0",
        "clients": 4
      },
      {
        "version": "2.18.1.0",
        "clients": 2
      },
      {
        "version": "2.17.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "prod",
    "clients": 483,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 483
      }
    ]
  },
  {
    "team": "majid-ai-futtaim",
    "clients": 248,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 247
      },
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "nykredit-realkredit",
    "clients": 235,
    "versions": [
      {
        "version": "2.13.0.0",
        "clients": 230
      },
      {
        "version": "2.21.1.0",
        "clients": 5
      }
    ]
  },
  {
    "team": "allstate",
    "clients": 212,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 196
      },
      {
        "version": "2.17.0.0",
        "clients": 14
      },
      {
        "version": "2.21.1.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "nec-corporation-2",
    "clients": 188,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 146
      },
      {
        "version": "2.20.0.0",
        "clients": 42
      }
    ]
  },
  {
    "team": "ofi-benelux-b-v--om-kaemingk-c4c",
    "clients": 176,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 176
      }
    ]
  },
  {
    "team": "production",
    "clients": 156,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 128
      },
      {
        "version": "2.10.0.0",
        "clients": 16
      },
      {
        "version": "2.15.2.0",
        "clients": 8
      },
      {
        "version": "2.12.0.0",
        "clients": 2
      },
      {
        "version": "2.17.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "kapitus",
    "clients": 139,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 82
      },
      {
        "version": "2.21.0.0",
        "clients": 47
      },
      {
        "version": "2.18.2.0",
        "clients": 4
      },
      {
        "version": "2.21.1.0",
        "clients": 4
      },
      {
        "version": "2.18.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "anglo-american",
    "clients": 131,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 88
      },
      {
        "version": "2.20.0.0",
        "clients": 24
      },
      {
        "version": "2.21.1.0",
        "clients": 10
      },
      {
        "version": "2.11.0.0",
        "clients": 6
      },
      {
        "version": "2.21.1.379",
        "clients": 1
      },
      {
        "version": "2.9.2.0",
        "clients": 1
      },
      {
        "version": "2.18.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "astrazeneca-dev",
    "clients": 102,
    "versions": [
      {
        "version": "2.17.0.0",
        "clients": 59
      },
      {
        "version": "2.18.0.0",
        "clients": 38
      },
      {
        "version": "2.20.0.0",
        "clients": 5
      }
    ]
  },
  {
    "team": "dbank",
    "clients": 68,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 68
      }
    ]
  },
  {
    "team": "mol",
    "clients": 61,
    "versions": [
      {
        "version": "2.17.1.251",
        "clients": 57
      },
      {
        "version": "2.18.1.0",
        "clients": 1
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      },
      {
        "version": "2.18.0.0",
        "clients": 1
      },
      {
        "version": "2.17.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "kimberlyclark",
    "clients": 55,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 31
      },
      {
        "version": "2.11.0.0",
        "clients": 6
      },
      {
        "version": "2.13.0.0",
        "clients": 4
      },
      {
        "version": "2.21.0.0",
        "clients": 4
      },
      {
        "version": "2.14.0.0",
        "clients": 3
      },
      {
        "version": "2.20.0.0",
        "clients": 2
      },
      {
        "version": "2.18.0.0",
        "clients": 2
      },
      {
        "version": "2.15.1.0",
        "clients": 1
      },
      {
        "version": "2.15.0.0",
        "clients": 1
      },
      {
        "version": "2.10.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "dai-ichi-life-insurance",
    "clients": 40,
    "versions": [
      {
        "version": "2.19.0.0",
        "clients": 40
      }
    ]
  },
  {
    "team": "aflac",
    "clients": 38,
    "versions": [
      {
        "version": "2.17.0.0",
        "clients": 18
      },
      {
        "version": "2.19.0.0",
        "clients": 13
      },
      {
        "version": "2.20.0.0",
        "clients": 5
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      },
      {
        "version": "2.15.2.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "schlumberger",
    "clients": 29,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 12
      },
      {
        "version": "2.18.2.0",
        "clients": 7
      },
      {
        "version": "2.18.0.0",
        "clients": 6
      },
      {
        "version": "2.18.1.0",
        "clients": 2
      },
      {
        "version": "2.17.1.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "task-mining",
    "clients": 28,
    "versions": [
      {
        "version": "anyClientVersion",
        "clients": 13
      },
      {
        "version": "2.22.0.0",
        "clients": 7
      },
      {
        "version": "2.21.1.0",
        "clients": 3
      },
      {
        "version": "2.20.0",
        "clients": 2
      },
      {
        "version": "2.7.6.0",
        "clients": 1
      },
      {
        "version": "0.0.0-sim",
        "clients": 1
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "manulife-pov-ca-pov",
    "clients": 26,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 26
      }
    ]
  },
  {
    "team": "toyo-seikan",
    "clients": 26,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 25
      },
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "caceis-task-mining-pov",
    "clients": 20,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 15
      },
      {
        "version": "2.21.1.0",
        "clients": 5
      }
    ]
  },
  {
    "team": "endpoint",
    "clients": 20,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 11
      },
      {
        "version": "2.21.1.0",
        "clients": 7
      },
      {
        "version": "2.18.2.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "fujitsu-limited-product-business-task-mining-c4c",
    "clients": 20,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 20
      }
    ]
  },
  {
    "team": "riverty",
    "clients": 19,
    "versions": [
      {
        "version": "2.18.0.0",
        "clients": 19
      }
    ]
  },
  {
    "team": "schlumberger-qa",
    "clients": 15,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 13
      },
      {
        "version": "2.13.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "task-mining-purple",
    "clients": 14,
    "versions": [
      {
        "version": "anyClientVersion",
        "clients": 12
      },
      {
        "version": "2.21.1.0",
        "clients": 1
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "kn-sb",
    "clients": 13,
    "versions": [
      {
        "version": "2.17.0.0",
        "clients": 10
      },
      {
        "version": "2.17.1.0",
        "clients": 2
      },
      {
        "version": "2.15.2.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "siemens-sandbox",
    "clients": 11,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 6
      },
      {
        "version": "2.21.1.0",
        "clients": 4
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "amgen",
    "clients": 10,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 4
      },
      {
        "version": "2.18.0.0",
        "clients": 4
      },
      {
        "version": "2.19.0.0",
        "clients": 1
      },
      {
        "version": "2.18.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "task-mining-ml-job",
    "clients": 10,
    "versions": [
      {
        "version": "anyClientVersion",
        "clients": 10
      }
    ]
  },
  {
    "team": "coloplast-pov",
    "clients": 8,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 8
      }
    ]
  },
  {
    "team": "ibm-crossmark-c4c",
    "clients": 8,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 7
      },
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "consulting",
    "clients": 7,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 7
      }
    ]
  },
  {
    "team": "task-mining-orange",
    "clients": 7,
    "versions": [
      {
        "version": "anyClientVersion",
        "clients": 7
      }
    ]
  },
  {
    "team": "upm-sandbox",
    "clients": 7,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 3
      },
      {
        "version": "2.21.1.0",
        "clients": 2
      },
      {
        "version": "2.18.2.0",
        "clients": 1
      },
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "banco-pichincha",
    "clients": 6,
    "versions": [
      {
        "version": "2.15.2.0",
        "clients": 6
      }
    ]
  },
  {
    "team": "dpdhl",
    "clients": 6,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 6
      }
    ]
  },
  {
    "team": "kistler-prod",
    "clients": 6,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 6
      }
    ]
  },
  {
    "team": "kn",
    "clients": 6,
    "versions": [
      {
        "version": "2.13.0.0",
        "clients": 6
      }
    ]
  },
  {
    "team": "pepsico-prod",
    "clients": 6,
    "versions": [
      {
        "version": "2.17.0.0",
        "clients": 4
      },
      {
        "version": "2.11.0.0",
        "clients": 1
      },
      {
        "version": "2.18.2.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "telefonica-productive",
    "clients": 6,
    "versions": [
      {
        "version": "2.6.1.0",
        "clients": 6
      }
    ]
  },
  {
    "team": "dbank-psb",
    "clients": 5,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 5
      }
    ]
  },
  {
    "team": "allianzconsult-prod",
    "clients": 4,
    "versions": [
      {
        "version": "2.18.1.0",
        "clients": 3
      },
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "envalior",
    "clients": 4,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 4
      }
    ]
  },
  {
    "team": "sandbox",
    "clients": 4,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 3
      },
      {
        "version": "2.10.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "unilever-genpact",
    "clients": 4,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 4
      }
    ]
  },
  {
    "team": "eight-japan-engineering-consultants",
    "clients": 3,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 3
      }
    ]
  },
  {
    "team": "merck-tst",
    "clients": 3,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 2
      },
      {
        "version": "2.10.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "payroll-task-mining",
    "clients": 3,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 3
      }
    ]
  },
  {
    "team": "productive",
    "clients": 3,
    "versions": [
      {
        "version": "2.6.1.0",
        "clients": 3
      }
    ]
  },
  {
    "team": "atth6lw3-2023-12-07",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      },
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "booking-holdings",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "dev",
    "clients": 2,
    "versions": [
      {
        "version": "2.22.0.0",
        "clients": 1
      },
      {
        "version": "2.21.2.384",
        "clients": 1
      }
    ]
  },
  {
    "team": "diot-siaci",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "gs-training-2026",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "itochu-partner-sandbox",
    "clients": 2,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 1
      },
      {
        "version": "2.19.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "metro-bank",
    "clients": 2,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      },
      {
        "version": "2.19.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "novartis-sb",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "ofi-benelux-bv-assistzorg-c4c",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "silamir-partner-sandbox",
    "clients": 2,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 2
      }
    ]
  },
  {
    "team": "2mi7vsyd-2025-11-18",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "6f1oiqjp-2026-02-13",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "90tcwbmd-2025-08-08",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "a-gutte-celonis-com",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "abeam-partner-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "accenture-development-sandbox-dcp",
    "clients": 1,
    "versions": [
      {
        "version": "2.6.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "banco-santander",
    "clients": 1,
    "versions": [
      {
        "version": "2.18.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "basf",
    "clients": 1,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "bouygues-telecom",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "bouygues-telecom-pov-network-pov",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "celonis-ryw9oc",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "cordesgraefe",
    "clients": 1,
    "versions": [
      {
        "version": "2.9.2.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "deloitte-in-partner-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.14.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "ems-japan-pov",
    "clients": 1,
    "versions": [
      {
        "version": "2.18.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "hitachi-partner-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "ibm-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.19.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "ihg-pov",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "kpdgk5yo-2025-12-12",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "logatik-partner-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "m-sakamoto-celonis-com",
    "clients": 1,
    "versions": [
      {
        "version": "2.19.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "michelin",
    "clients": 1,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "mondelez",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "nationwide-prod",
    "clients": 1,
    "versions": [
      {
        "version": "2.18.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "nomura-research-institute-partner-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "optus-standard-sandbox",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "panasonic-information",
    "clients": 1,
    "versions": [
      {
        "version": "2.18.2.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "pyze-partner-sandbox2",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "rabobank",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "rabobank-sb",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.0.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "secpentest-1",
    "clients": 1,
    "versions": [
      {
        "version": "2.20.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "syngenta-prod",
    "clients": 1,
    "versions": [
      {
        "version": "2.8.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "task-mining-demo---kay",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "tgt-internal",
    "clients": 1,
    "versions": [
      {
        "version": "2.21.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "wilo-sb",
    "clients": 1,
    "versions": [
      {
        "version": "2.17.1.0",
        "clients": 1
      }
    ]
  },
  {
    "team": "workday",
    "clients": 1,
    "versions": [
      {
        "version": "2.3.0.0",
        "clients": 1
      }
    ]
  }
];
