// Recorder version adoption per customer, from Datadog (service:task-mining).
// Period: Jul 27 - Aug 10, 2026. Distinct @clientId per (@teamDomain, @recorderVersion).
// Generated by scripts/refresh_aug10.py - do not edit by hand.

import type { VersionPoint } from "@/data/adoption";

export const VERSION_PERIOD = "Jul 27 - Aug 10, 2026";

export const versionTotals: VersionPoint[] = [
  { version: "2.21.1.0", clients: 2546 },
  { version: "2.21.0.0", clients: 1162 },
  { version: "2.20.0.0", clients: 878 },
  { version: "2.18.2.0", clients: 310 },
  { version: "2.17.1.0", clients: 166 },
  { version: "2.17.0.0", clients: 86 },
  { version: "2.18.0.0", clients: 62 },
  { version: "2.17.1.251", clients: 55 },
  { version: "2.18.1.0", clients: 53 },
  { version: "2.19.0.0", clients: 49 },
  { version: "2.21.2.0", clients: 43 },
  { version: "2.15.2.0", clients: 18 },
  { version: "2.10.0.0", clients: 15 },
  { version: "2.13.0.0", clients: 11 },
  { version: "2.20.1.0", clients: 10 },
  { version: "2.6.1.0", clients: 10 },
  { version: "2.11.0.0", clients: 6 },
  { version: "2.9.2.0", clients: 2 },
  { version: "2.14.0.0", clients: 2 },
  { version: "2.21.2.384", clients: 1 },
  { version: "2.15.1.0", clients: 1 },
  { version: "2.12.0.0", clients: 1 },
  { version: "2.21.1.379", clients: 1 },
  { version: "2.8.1.0", clients: 1 },
  { version: "2.7.6.0", clients: 1 },
];

export interface TeamVersions {
  team: string;
  clients: number;
  versions: VersionPoint[];
}

export const versionsByTeam: TeamVersions[] = [
  {
    team: "nykredit-realkredit",
    clients: 1814,
    versions: [
      { version: "2.21.1.0", clients: 1813 },
      { version: "2.13.0.0", clients: 1 },
    ],
  },
  {
    team: "majid-ai-futtaim",
    clients: 812,
    versions: [
      { version: "2.21.0.0", clients: 809 },
      { version: "2.21.1.0", clients: 2 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "prod",
    clients: 453,
    versions: [
      { version: "2.20.0.0", clients: 453 },
    ],
  },
  {
    team: "allianz-global",
    clients: 377,
    versions: [
      { version: "2.21.1.0", clients: 330 },
      { version: "2.18.1.0", clients: 45 },
      { version: "2.21.0.0", clients: 1 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "refinitiv",
    clients: 327,
    versions: [
      { version: "2.18.2.0", clients: 297 },
      { version: "2.17.1.0", clients: 24 },
      { version: "2.15.2.0", clients: 4 },
      { version: "2.17.0.0", clients: 1 },
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "allstate",
    clients: 191,
    versions: [
      { version: "2.20.0.0", clients: 178 },
      { version: "2.17.0.0", clients: 11 },
      { version: "2.21.1.0", clients: 2 },
    ],
  },
  {
    team: "nec-corporation-2",
    clients: 188,
    versions: [
      { version: "2.21.0.0", clients: 147 },
      { version: "2.20.0.0", clients: 40 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "ofi-benelux-b-v--om-kaemingk-c4c",
    clients: 168,
    versions: [
      { version: "2.21.1.0", clients: 168 },
    ],
  },
  {
    team: "kapitus",
    clients: 166,
    versions: [
      { version: "2.21.0.0", clients: 83 },
      { version: "2.20.0.0", clients: 70 },
      { version: "2.21.1.0", clients: 6 },
      { version: "2.18.2.0", clients: 4 },
      { version: "2.18.0.0", clients: 2 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "anglo-american",
    clients: 161,
    versions: [
      { version: "2.21.0.0", clients: 81 },
      { version: "2.21.1.0", clients: 36 },
      { version: "2.20.0.0", clients: 19 },
      { version: "2.21.2.0", clients: 17 },
      { version: "2.11.0.0", clients: 5 },
      { version: "2.18.1.0", clients: 1 },
      { version: "2.21.1.379", clients: 1 },
      { version: "2.9.2.0", clients: 1 },
    ],
  },
  {
    team: "production",
    clients: 131,
    versions: [
      { version: "2.17.1.0", clients: 108 },
      { version: "2.10.0.0", clients: 14 },
      { version: "2.15.2.0", clients: 8 },
      { version: "2.12.0.0", clients: 1 },
    ],
  },
  {
    team: "astrazeneca-dev",
    clients: 89,
    versions: [
      { version: "2.17.0.0", clients: 50 },
      { version: "2.18.0.0", clients: 35 },
      { version: "2.20.0.0", clients: 4 },
    ],
  },
  {
    team: "dbank",
    clients: 69,
    versions: [
      { version: "2.20.0.0", clients: 69 },
    ],
  },
  {
    team: "mol",
    clients: 59,
    versions: [
      { version: "2.17.1.251", clients: 55 },
      { version: "2.18.0.0", clients: 1 },
      { version: "2.21.0.0", clients: 1 },
      { version: "2.17.1.0", clients: 1 },
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "unilever-genpact",
    clients: 38,
    versions: [
      { version: "2.21.1.0", clients: 38 },
    ],
  },
  {
    team: "dai-ichi-life-insurance",
    clients: 36,
    versions: [
      { version: "2.19.0.0", clients: 36 },
    ],
  },
  {
    team: "schlumberger",
    clients: 28,
    versions: [
      { version: "2.20.0.0", clients: 13 },
      { version: "2.18.0.0", clients: 8 },
      { version: "2.18.2.0", clients: 5 },
      { version: "2.17.1.0", clients: 1 },
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "toyo-seikan",
    clients: 26,
    versions: [
      { version: "2.21.1.0", clients: 26 },
    ],
  },
  {
    team: "manulife-pov-ca-pov",
    clients: 24,
    versions: [
      { version: "2.21.1.0", clients: 24 },
    ],
  },
  {
    team: "aflac",
    clients: 22,
    versions: [
      { version: "2.17.0.0", clients: 11 },
      { version: "2.19.0.0", clients: 8 },
      { version: "2.20.0.0", clients: 2 },
      { version: "2.21.0.0", clients: 1 },
    ],
  },
  {
    team: "kimberlyclark",
    clients: 22,
    versions: [
      { version: "2.21.1.0", clients: 13 },
      { version: "2.20.0.0", clients: 2 },
      { version: "2.14.0.0", clients: 2 },
      { version: "2.18.0.0", clients: 2 },
      { version: "2.21.2.0", clients: 1 },
      { version: "2.15.1.0", clients: 1 },
      { version: "2.13.0.0", clients: 1 },
    ],
  },
  {
    team: "elsevier",
    clients: 20,
    versions: [
      { version: "2.21.1.0", clients: 20 },
    ],
  },
  {
    team: "fujitsu-limited-product-business-task-mining-c4c",
    clients: 19,
    versions: [
      { version: "2.21.0.0", clients: 19 },
    ],
  },
  {
    team: "caceis-task-mining-pov",
    clients: 16,
    versions: [
      { version: "2.21.0.0", clients: 7 },
      { version: "2.21.1.0", clients: 6 },
      { version: "2.21.2.0", clients: 3 },
    ],
  },
  {
    team: "endpoint",
    clients: 16,
    versions: [
      { version: "2.17.1.0", clients: 10 },
      { version: "2.21.1.0", clients: 4 },
      { version: "2.18.2.0", clients: 2 },
    ],
  },
  {
    team: "siemens-sandbox",
    clients: 16,
    versions: [
      { version: "2.21.1.0", clients: 5 },
      { version: "2.20.1.0", clients: 5 },
      { version: "2.21.2.0", clients: 5 },
      { version: "2.21.0.0", clients: 1 },
    ],
  },
  {
    team: "schlumberger-qa",
    clients: 14,
    versions: [
      { version: "2.17.1.0", clients: 12 },
      { version: "2.13.0.0", clients: 2 },
    ],
  },
  {
    team: "coloplast-pov",
    clients: 12,
    versions: [
      { version: "2.21.1.0", clients: 12 },
    ],
  },
  {
    team: "kn-sb",
    clients: 12,
    versions: [
      { version: "2.17.0.0", clients: 9 },
      { version: "2.17.1.0", clients: 2 },
      { version: "2.15.2.0", clients: 1 },
    ],
  },
  {
    team: "amgen",
    clients: 11,
    versions: [
      { version: "2.18.0.0", clients: 5 },
      { version: "2.20.0.0", clients: 4 },
      { version: "2.19.0.0", clients: 1 },
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "novartis-sb",
    clients: 9,
    versions: [
      { version: "2.21.1.0", clients: 9 },
    ],
  },
  {
    team: "consulting",
    clients: 8,
    versions: [
      { version: "2.21.1.0", clients: 8 },
    ],
  },
  {
    team: "kn",
    clients: 7,
    versions: [
      { version: "2.13.0.0", clients: 7 },
    ],
  },
  {
    team: "dpdhl",
    clients: 6,
    versions: [
      { version: "2.20.0.0", clients: 6 },
    ],
  },
  {
    team: "eon",
    clients: 6,
    versions: [
      { version: "2.21.2.0", clients: 4 },
      { version: "2.21.1.0", clients: 1 },
      { version: "2.20.0.0", clients: 1 },
    ],
  },
  {
    team: "pepsico-prod",
    clients: 6,
    versions: [
      { version: "2.17.0.0", clients: 4 },
      { version: "2.18.2.0", clients: 1 },
      { version: "2.11.0.0", clients: 1 },
    ],
  },
  {
    team: "riverty",
    clients: 6,
    versions: [
      { version: "2.18.0.0", clients: 6 },
    ],
  },
  {
    team: "telefonica-productive",
    clients: 6,
    versions: [
      { version: "2.6.1.0", clients: 6 },
    ],
  },
  {
    team: "banco-pichincha",
    clients: 5,
    versions: [
      { version: "2.15.2.0", clients: 5 },
    ],
  },
  {
    team: "ibm-crossmark-c4c",
    clients: 5,
    versions: [
      { version: "2.17.1.0", clients: 5 },
    ],
  },
  {
    team: "sandbox",
    clients: 5,
    versions: [
      { version: "2.21.2.0", clients: 2 },
      { version: "2.20.0.0", clients: 2 },
      { version: "2.10.0.0", clients: 1 },
    ],
  },
  {
    team: "upm-sandbox",
    clients: 5,
    versions: [
      { version: "2.20.1.0", clients: 3 },
      { version: "2.21.1.0", clients: 2 },
    ],
  },
  {
    team: "bouygues-telecom",
    clients: 4,
    versions: [
      { version: "2.21.1.0", clients: 4 },
    ],
  },
  {
    team: "envalior",
    clients: 4,
    versions: [
      { version: "2.20.0.0", clients: 4 },
    ],
  },
  {
    team: "kistler-prod",
    clients: 4,
    versions: [
      { version: "2.21.0.0", clients: 4 },
    ],
  },
  {
    team: "alstom",
    clients: 3,
    versions: [
      { version: "2.21.1.0", clients: 2 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "eight-japan-engineering-consultants",
    clients: 3,
    versions: [
      { version: "2.20.0.0", clients: 3 },
    ],
  },
  {
    team: "merck-tst",
    clients: 3,
    versions: [
      { version: "2.20.0.0", clients: 3 },
    ],
  },
  {
    team: "productive",
    clients: 3,
    versions: [
      { version: "2.6.1.0", clients: 3 },
    ],
  },
  {
    team: "booking-holdings",
    clients: 2,
    versions: [
      { version: "2.21.0.0", clients: 2 },
    ],
  },
  {
    team: "cel-tm-finance",
    clients: 2,
    versions: [
      { version: "2.21.2.384", clients: 1 },
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "dbank-psb",
    clients: 2,
    versions: [
      { version: "2.20.0.0", clients: 2 },
    ],
  },
  {
    team: "diot-siaci",
    clients: 2,
    versions: [
      { version: "2.21.0.0", clients: 2 },
    ],
  },
  {
    team: "itochu-partner-sandbox",
    clients: 2,
    versions: [
      { version: "2.20.1.0", clients: 1 },
      { version: "2.19.0.0", clients: 1 },
    ],
  },
  {
    team: "payroll-task-mining",
    clients: 2,
    versions: [
      { version: "2.21.1.0", clients: 2 },
    ],
  },
  {
    team: "silamir-partner-sandbox",
    clients: 2,
    versions: [
      { version: "2.21.0.0", clients: 2 },
    ],
  },
  {
    team: "task-mining",
    clients: 2,
    versions: [
      { version: "2.21.1.0", clients: 1 },
      { version: "2.7.6.0", clients: 1 },
    ],
  },
  {
    team: "task-mining-demo---kay",
    clients: 2,
    versions: [
      { version: "2.21.1.0", clients: 1 },
      { version: "2.18.0.0", clients: 1 },
    ],
  },
  {
    team: "a-gutte-celonis-com",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "accenture-development-sandbox-dcp",
    clients: 1,
    versions: [
      { version: "2.6.1.0", clients: 1 },
    ],
  },
  {
    team: "allianzconsult-prod",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "axa-task-mining",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "banco-santander",
    clients: 1,
    versions: [
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "basf",
    clients: 1,
    versions: [
      { version: "2.17.1.0", clients: 1 },
    ],
  },
  {
    team: "bouygues-telecom-pov-network-pov",
    clients: 1,
    versions: [
      { version: "2.20.0.0", clients: 1 },
    ],
  },
  {
    team: "celonis-rktu9q",
    clients: 1,
    versions: [
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "ciklum-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "cordesgraefe",
    clients: 1,
    versions: [
      { version: "2.9.2.0", clients: 1 },
    ],
  },
  {
    team: "dataops",
    clients: 1,
    versions: [
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "ems-japan-pov",
    clients: 1,
    versions: [
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "fnfh2u42-2025-04-18",
    clients: 1,
    versions: [
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "hanwhasolution-pov",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "hitachi-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "ibm-sandbox",
    clients: 1,
    versions: [
      { version: "2.19.0.0", clients: 1 },
    ],
  },
  {
    team: "ilt-saint-gobain-training",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "jc14jlpc-2026-04-03",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "kone",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "kpdgk5yo-2025-12-12",
    clients: 1,
    versions: [
      { version: "2.20.1.0", clients: 1 },
    ],
  },
  {
    team: "logatik-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.0.0", clients: 1 },
    ],
  },
  {
    team: "m-sakamoto-celonis-com",
    clients: 1,
    versions: [
      { version: "2.19.0.0", clients: 1 },
    ],
  },
  {
    team: "metro-bank",
    clients: 1,
    versions: [
      { version: "2.19.0.0", clients: 1 },
    ],
  },
  {
    team: "michelin",
    clients: 1,
    versions: [
      { version: "2.17.1.0", clients: 1 },
    ],
  },
  {
    team: "mondelez",
    clients: 1,
    versions: [
      { version: "2.20.0.0", clients: 1 },
    ],
  },
  {
    team: "nationwide-prod",
    clients: 1,
    versions: [
      { version: "2.18.0.0", clients: 1 },
    ],
  },
  {
    team: "nomura-research-institute-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.20.0.0", clients: 1 },
    ],
  },
  {
    team: "optus-standard-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.0.0", clients: 1 },
    ],
  },
  {
    team: "panasonic-information",
    clients: 1,
    versions: [
      { version: "2.18.2.0", clients: 1 },
    ],
  },
  {
    team: "pyze-partner-sandbox2",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "roboyo-us-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.2.0", clients: 1 },
    ],
  },
  {
    team: "syngenta-prod",
    clients: 1,
    versions: [
      { version: "2.8.1.0", clients: 1 },
    ],
  },
  {
    team: "tata-consultancy-services-partner-sandbox",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "tgt-internal",
    clients: 1,
    versions: [
      { version: "2.21.1.0", clients: 1 },
    ],
  },
  {
    team: "tpl-product-task-mining",
    clients: 1,
    versions: [
      { version: "2.18.1.0", clients: 1 },
    ],
  },
  {
    team: "wilo-sb",
    clients: 1,
    versions: [
      { version: "2.17.1.0", clients: 1 },
    ],
  },
  {
    team: "zespri",
    clients: 1,
    versions: [
      { version: "2.18.0.0", clients: 1 },
    ],
  },
];
